---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    facing: worker
    service: pbeb
    type: mispyebooks
  name: pbeb-mispyebooks-v0
spec:
  replicas: 1
  selector:
    service: pbeb
    type: mispyebooks
    version: v0
  template:
    metadata:
      labels:
        service: pbeb
        type: mispyebooks
        version: v0
    spec:
      containers:
        -
          image: quay.io/purplebooth/purplebo_ebooks
          imagePullPolicy: Always
          name: pbeb-mispyebooks
          env:
            - name: SECRETS_PATH
              value: /secrets/purplebo-ebooks.cfg
          volumeMounts:
            -
              mountPath: /secrets
              name: twitter-secrets
      restartPolicy: Always
      volumes:
        -
          name: twitter-secrets
          secret:
            secretName: twitter-secrets
